spring:
  profiles:
    active: local
grpc:
  client:
    stubs:
      - clazz: com.seezoon.helloworld.HelloWorldGrpc.HelloWorldStub
        channel: hello_world_server
      - clazz: com.seezoon.helloworld.HelloWorldGrpc.HelloWorldBlockingStub
        channel: hello_world_server
      - clazz: com.seezoon.helloworld.HelloWorldGrpc.HelloWorldFutureStub
        channel: hello_world_server